updates

diff --git a/bin/bin/ai b/bin/bin/ai
--- a/bin/bin/ai
+++ b/bin/bin/ai
@@ -1,12 +1,16 @@
 #!/bin/bash
 root_dir="$HOME"/src/ai
 
+if ! [[ -f "$root_dir"/.venv/pyvenv.cfg ]]; then
+  die "no ai virtualenv exists 'root_dir=$root_dir'. try running '$root_dir/setup-env'"
+fi
+
 # shellcheck disable=SC1091
 . "$root_dir"/.venv/bin/activate
-. "$root_dir"/.env
 
 if (( 0 )) && [[ "$PWD" != "$root_dir" ]] && command -v rlwrap 2>/dev/null >/dev/null; then
   exec rlwrap ai "$@"
 else
-  exec ai "$@"
+  cd "$root_dir"/src || die "failed to cd"
+  exec python -m ai.cli "$@"
 fi
